# Generated by Django 5.2.4 on 2025-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, max_length=200),
        ),
    ]
