# Generated by Django 5.2.4 on 2025-07-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskhistory'),
    ]

    operations = [
    ]
