# Generated by Django 5.2.4 on 2025-07-15 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_taskhistory_user_alter_taskhistory_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='task_priority',
            field=models.CharField(default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task_status',
            field=models.CharField(default='Pending', max_length=15),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task_title',
            field=models.CharField(default='(No title)', max_length=200),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated'), ('Deleted', 'Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasks'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_histories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
